name: CD action

on:
  repository_dispatch:
    types:
      - update-manifest

jobs:
  build-and-push:
    runs-on: ubuntu-18.04

    env:
      SHA: ${{ github.event.client_payload.sha }}

    steps:
      - name: Update manifest
        uses: mikefarah/yq@master
        with:
          cmd: yq write -i go-sample/deployment.yaml 'spec.template.spec.containers[0].image' '${{ secrets.AWS_ECR_REPO_NAME }}:${{ env.SHA }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            update container image
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/dev
          base: main
          delete-branch: true
          title: |
            Update Container Image
          body: |
            Update Container Image
            - Updated helm chart container image
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
          assignees: tomoyasuzuki
          draft: false